/**
* @description a util class for storing Constants
*/
const getConstants = () =>{
   return {
    FIRST_NAME : 'First name',
    LAST_NAME : 'Last name',
    EMAIL : 'Email',
    ROLE:'Role',
    SCHOOL_OPTIONS:'Do you need a quote for your school, or the district?',
    CITY:'City',
    SCHOOL_ENROLLMENT:'What is your school enrollment?',
    PURCHASE_OPTIONS:'Do you need a quote for the entire district or just certain schools?',
    SCHOOL_COUNT:'How many schools do you need a quote for?',
    SEARCH_SCHOOL:'Search for your school',
    SEARCH_DISTRICT:'Search District',
    SCHOOL:'School',
    DISTRICT:'District',
    CERTAIN_SCHOOL:'Certain Schools',
    PUBLIC_SCHOOL:'Public School',
    CHARTER_SCHOOL:'Charter School',
    PRIVATE_SCHOOL:'Private School',
    SCHOOL_TYPE:'School',
    DISTRICT_TYPE:'District',
    PUBLIC_DISTRICT:'Public District',
    CONTRACT_TYPE:'Contract_Type__c',
    FORM_SUBMISSION_CONTRACT_TYPE : "Form_Submission_Contract_Type__c",
    MAILING_CITY:'MailingCity',
    ENTIRE_DISTRICT:'Entire District',
    ACCOUNT_ID:'AccountId',
    USA:'United States',
    INTERNATIONAL:'Outside of the U.S.',
    REGION:'Country',
    REGION_API:'Region__c',
    COUNTRY:'Country',
    SCHOOL_NAME:'School Name',
    SCHOOL_CITY: 'School City',
    SCHOOL_STATE: 'School State',
    DISTRICT_NAME:'District Name',
    DISTRICT_CITY: 'District City',
    DISTRICT_STATE: 'District State',
    DISTRICT_ENROLLMENT: 'How many schools are in your district?',
    ADDITIONAL_INFORMATION:'Anything else you\'d like to share?',
    PURCHASE:'purchase',
    OTHER:'Other',
    ROLE_API:'Role__c',
    OTHER_ROLE_LABEL:'What is your role?',
    ZIPCODE_LABEL:'What is your zip code?',
    ZIPCODE_ERROR_MESSAGE:'Please enter a valid zip code',
    EMAIL_ERROR_MESSAGE:'Please enter a valid email address',
    EMPTY_ACCOUNT_ERROR_MESSAGE:'Please select a school'
  }
}

export { getConstants };